#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Summary Logger Module

This module handles automatic generation and saving of summary statistics
based on user interactions with the application. Following the modular architecture,
it creates and updates summary CSV files in the appropriate processed data directories.
"""

import os
import pandas as pd
import numpy as np
import json
import datetime
from pathlib import Path
import csv

class SummaryLogger:
    """
    Logs application usage and generates summary statistics based on user interactions.
    
    This class maintains the project's preference for storing summary statistics
    alongside the data processing logic, ensuring all insights are properly
    documented and saved.
    """
    
    def __init__(self, project_root):
        """
        Initialize the summary logger.
        
        Args:
            project_root (Path): Path to the project root directory.
        """
        self.project_root = project_root
        self.processed_data_dir = project_root / "data" / "processed"
        self.summary_dir = self.processed_data_dir / "summary"
        
        # Create summary directory if it doesn't exist
        os.makedirs(self.summary_dir, exist_ok=True)
        
        # Initialize log files
        self.interaction_log_file = self.summary_dir / "user_interactions.csv"
        self.insight_log_file = self.summary_dir / "agent_insights.csv"
        self.prediction_log_file = self.summary_dir / "prediction_results.csv"
        
        # Initialize log files if they don't exist
        self._initialize_log_files()
    
    def _initialize_log_files(self):
        """Initialize log files with headers if they don't exist."""
        # User interactions log
        if not os.path.exists(self.interaction_log_file):
            with open(self.interaction_log_file, 'w', newline='') as f:
                writer = csv.writer(f)
                writer.writerow(['timestamp', 'page', 'action', 'details'])
        
        # Agent insights log
        if not os.path.exists(self.insight_log_file):
            with open(self.insight_log_file, 'w', newline='') as f:
                writer = csv.writer(f)
                writer.writerow(['timestamp', 'insight_type', 'title', 'description'])
        
        # Prediction results log
        if not os.path.exists(self.prediction_log_file):
            with open(self.prediction_log_file, 'w', newline='') as f:
                writer = csv.writer(f)
                writer.writerow(['timestamp', 'neighborhood', 'scenario', 'current_ratio', 'predicted_ratio', 'change'])
    
    def log_interaction(self, page, action, details=None):
        """
        Log a user interaction with the application.
        
        Args:
            page (str): The page where the interaction occurred
            action (str): The action the user took
            details (dict, optional): Additional details about the interaction
        """
        timestamp = datetime.datetime.now().isoformat()
        details_str = json.dumps(details) if details else ""
        
        with open(self.interaction_log_file, 'a', newline='') as f:
            writer = csv.writer(f)
            writer.writerow([timestamp, page, action, details_str])
    
    def log_insight(self, insight_type, title, description):
        """
        Log an insight generated by the agent.
        
        Args:
            insight_type (str): Type of insight (e.g., 'initial', 'proactive')
            title (str): Title of the insight
            description (str): Description of the insight
        """
        timestamp = datetime.datetime.now().isoformat()
        
        with open(self.insight_log_file, 'a', newline='') as f:
            writer = csv.writer(f)
            writer.writerow([timestamp, insight_type, title, description])
    
    def log_prediction(self, neighborhood, scenario, current_ratio, predicted_ratio):
        """
        Log a prediction made by the application.
        
        Args:
            neighborhood (str): The neighborhood being analyzed
            scenario (str): The scenario being modeled
            current_ratio (float): Current rent-to-income ratio
            predicted_ratio (float): Predicted rent-to-income ratio
        """
        timestamp = datetime.datetime.now().isoformat()
        change = predicted_ratio - current_ratio
        
        with open(self.prediction_log_file, 'a', newline='') as f:
            writer = csv.writer(f)
            writer.writerow([timestamp, neighborhood, scenario, current_ratio, predicted_ratio, change])
    
    def generate_summary_stats(self):
        """
        Generate summary statistics from the logs and save to CSV.
        
        This follows the project's modular approach of generating summary statistics
        immediately after data processing.
        """
        # Timestamp for the summary files
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        
        # Generate interaction summary
        if os.path.exists(self.interaction_log_file):
            try:
                interactions_df = pd.read_csv(self.interaction_log_file)
                
                # Generate summary by page
                page_summary = interactions_df['page'].value_counts().reset_index()
                page_summary.columns = ['page', 'count']
                
                # Save summary
                summary_file = self.summary_dir / f"summary_interactions_{timestamp}.csv"
                page_summary.to_csv(summary_file, index=False)
            except Exception as e:
                print(f"Error generating interaction summary: {e}")
        
        # Generate prediction summary
        if os.path.exists(self.prediction_log_file):
            try:
                predictions_df = pd.read_csv(self.prediction_log_file)
                
                if not predictions_df.empty:
                    # Calculate average change by scenario
                    scenario_summary = predictions_df.groupby('scenario')['change'].agg(
                        ['mean', 'median', 'std', 'count']
                    ).reset_index()
                    
                    # Save summary
                    summary_file = self.summary_dir / f"summary_predictions_{timestamp}.csv"
                    scenario_summary.to_csv(summary_file, index=False)
            except Exception as e:
                print(f"Error generating prediction summary: {e}")
    
    def export_insights_to_csv(self):
        """
        Export collected agent insights to a formatted CSV file.
        
        This is useful for stakeholders who want to review the key insights
        discovered during the analysis.
        """
        if os.path.exists(self.insight_log_file):
            try:
                insights_df = pd.read_csv(self.insight_log_file)
                
                # Process and format insights
                formatted_df = insights_df[['timestamp', 'title', 'description']]
                
                # Save as a stakeholder-friendly CSV
                export_file = self.project_root / "Presentation" / "key_insights.csv"
                formatted_df.to_csv(export_file, index=False)
                
                return export_file
            except Exception as e:
                print(f"Error exporting insights: {e}")
                return None
